name: 'coverage'
on:
  push:
    branches:
      - master
      - main
      - next
      - canary
  pull_request:
    branches:
      - master
      - main
      - next
      - canary

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    env:
      CI_JOB_NUMBER: 1
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@master
        with:
          node-version: 16
      - name: install
        run: |
          yarn add -W -D typescript@next ts-jest
          yarn install --frozen-lockfile
      - uses: artiomtr/jest-coverage-report-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          package-manager: yarn
#          test-script: npx --yes --package ts-jest --package jest jest --silent --ci --coverage --testLocationInResults --json --outputFile="report.json"
          #   threshold: 80 # optional parameter
